<a href="https://colab.research.google.com/github/PiotrSzewerniak/data-science/blob/main/intro.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [2]:
import numpy as np
np.__version__

'1.23.5'

In [ ]:
print(dir(np))

In [ ]:
help(np.array)

1D Array

In [8]:
x = np.array([1, 3])
x

array([1, 3])

In [9]:
print(x)

[1 3]


In [10]:
type(x)

numpy.ndarray

In [11]:
x.ndim

1

In [12]:
x.shape

(2,)

In [13]:
x.size

2

In [14]:
x.dtype

dtype('int64')

In [18]:
x=np.array([1.3, 2.3, 1.4])
print(x)

[1.3 2.3 1.4]


In [19]:
x.dtype

dtype('float64')

2D Array

In [24]:
x = np.array([[1, 2], [-3, 1]])
x

array([[ 1,  2],
       [-3,  1]])

In [22]:
x.ndim

2

In [23]:
x.shape

(2, 2)

In [25]:
x = np.array([[1, 2, 4], [4, 2, 1]])
print(x)

[[1 2 4]
 [4 2 1]]


In [26]:
x.shape

(2, 3)

3D Array

In [28]:
x = np.array(
    [[[4, 3, 1],
      [3, 1, 2]],

     [[4, 1, 3],
      [4, 2, 1]]]
    )
x

array([[[4, 3, 1],
        [3, 1, 2]],

       [[4, 1, 3],
        [4, 2, 1]]])

In [30]:
x.ndim

3

In [31]:
x.shape

(2, 2, 3)

Data types

In [32]:
A = np.array([1, 2, 3])
A.dtype

dtype('int64')

In [34]:
A = np.array([1.0, 2.3, 3.3])
A.dtype

dtype('float64')

In [36]:
A = np.array([1, 2, 3], dtype = "complex")
A.dtype

dtype('complex128')

In [40]:
A = np.array([1.0, 2.7, 3.3], dtype = "int")
A.dtype

dtype('int64')

In [41]:
A

array([1, 2, 3])

In [42]:
A = np.array([True, False])
A.dtype

dtype('bool')

In [44]:
A = np.array([24, 120, 230], dtype = np.uint8)
A.dtype

dtype('uint8')

Creating tables

In [45]:
np.zeros(shape = (4, 10))

array([[0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.]])

In [46]:
np.ones(shape = (5, 5))

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [47]:
np.full(shape = (3, 3), fill_value = 4, dtype = "int")

array([[4, 4, 4],
       [4, 4, 4],
       [4, 4, 4]])

In [49]:
np.arange(10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [50]:
np.arange(start = 5, stop = 10)

array([5, 6, 7, 8, 9])

In [51]:
np.arange(start = 10, stop = 100, step = 10)

array([10, 20, 30, 40, 50, 60, 70, 80, 90])

In [52]:
np.arange(start = 100, stop = 10, step = -10)

array([100,  90,  80,  70,  60,  50,  40,  30,  20])

In [53]:
np.linspace(start = 0, stop = 1, num = 11)

array([0. , 0.1, 0.2, 0.3, 0.4, 0.5, 0.6, 0.7, 0.8, 0.9, 1. ])

In [54]:
A = np.arange(15)
A

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [55]:
A.reshape((3, 5))

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]])

In [56]:
A.reshape((-1, 3))

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11],
       [12, 13, 14]])

Basic operations on arrays

In [3]:
A = np.array([3, 1, 4, 2])
B = np.array([3, -1, 3, 2])
print(A)
print(B)

[3 1 4 2]
[ 3 -1  3  2]


In [4]:
A + B

array([6, 0, 7, 4])

In [5]:
A - B

array([0, 2, 1, 0])

In [6]:
A * B

array([ 9, -1, 12,  4])

In [7]:
A / B

array([ 1.        , -1.        ,  1.33333333,  1.        ])

In [8]:
A + 3

array([6, 4, 7, 5])

In [9]:
2 * A

array([6, 2, 8, 4])

In [10]:
A + 3 * B

array([12, -2, 13,  8])

In [11]:
np.add(A, B)

array([6, 0, 7, 4])

In [12]:
np.subtract(A, B)

array([0, 2, 1, 0])

In [13]:
np.multiply(A, B)

array([ 9, -1, 12,  4])

In [14]:
np.divide(A, B)

array([ 1.        , -1.        ,  1.33333333,  1.        ])

In [17]:
X = np.array([[1, 3], [-2, 0]])
Y = np.array([[6, 0], [-1, 2]])
print(X, '\n')
print(Y)

[[ 1  3]
 [-2  0]] 

[[ 6  0]
 [-1  2]]


In [18]:
X * Y

array([[6, 0],
       [2, 0]])

In [19]:
np.dot(X, Y)

array([[  3,   6],
       [-12,   0]])

In [20]:
X.dot(Y)

array([[  3,   6],
       [-12,   0]])

In [21]:
X @ Y

array([[  3,   6],
       [-12,   0]])

Pseudo random

In [22]:
np.random.seed(0)

In [23]:
np.random.rand()

0.5488135039273248

In [24]:
np.random.randn(10)

array([ 0.74159174,  1.55291372, -2.2683282 ,  1.33354538, -0.84272405,
        1.96992445,  1.26611853, -0.50587654,  2.54520078,  1.08081191])

In [25]:
np.random.rand(10, 4)

array([[0.92559664, 0.07103606, 0.0871293 , 0.0202184 ],
       [0.83261985, 0.77815675, 0.87001215, 0.97861834],
       [0.79915856, 0.46147936, 0.78052918, 0.11827443],
       [0.63992102, 0.14335329, 0.94466892, 0.52184832],
       [0.41466194, 0.26455561, 0.77423369, 0.45615033],
       [0.56843395, 0.0187898 , 0.6176355 , 0.61209572],
       [0.616934  , 0.94374808, 0.6818203 , 0.3595079 ],
       [0.43703195, 0.6976312 , 0.06022547, 0.66676672],
       [0.67063787, 0.21038256, 0.1289263 , 0.31542835],
       [0.36371077, 0.57019677, 0.43860151, 0.98837384]])

In [26]:
np.random.rand()

0.10204481074802807

In [27]:
np.random.rand(10)

array([0.20887676, 0.16130952, 0.65310833, 0.2532916 , 0.46631077,
       0.24442559, 0.15896958, 0.11037514, 0.65632959, 0.13818295])

In [28]:
np.random.rand(10, 2)

array([[0.19658236, 0.36872517],
       [0.82099323, 0.09710128],
       [0.83794491, 0.09609841],
       [0.97645947, 0.4686512 ],
       [0.97676109, 0.60484552],
       [0.73926358, 0.03918779],
       [0.28280696, 0.12019656],
       [0.2961402 , 0.11872772],
       [0.31798318, 0.41426299],
       [0.0641475 , 0.69247212]])

In [30]:
np.random.randint(10)

4

In [31]:
np.random.randint(low = 10, high = 101, size = 10)

array([91, 60, 37, 24, 51, 68, 75, 46, 20, 96])

In [35]:
np.random.choice([4, 2, 1, 4])

1

In [36]:
np.random.choice(["python", "java", "sql"])

'python'

In [38]:
data = np.arange(10)
data

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [41]:
np.random.shuffle(data)
data

array([8, 1, 3, 7, 5, 4, 2, 9, 6, 0])

Basic functions

In [42]:
np.exp(1)

2.718281828459045

In [43]:
np.sqrt(9)

3.0

In [44]:
np.all([2, 3, 1])

True

In [46]:
np.any([1, 2, 1])

True

In [47]:
bool(0)

False

In [49]:
A = np.random.rand(5)
A

array([0.39650574, 0.8811032 , 0.58127287, 0.88173536, 0.69253159])

In [50]:
np.argmax(A)

3

In [51]:
A[np.argmax(A)]

0.8817353618548528

In [52]:
np.argmin(A)

0

In [53]:
np.argsort(A)

array([0, 2, 4, 1, 3])

In [54]:
np.max(A)

0.8817353618548528

In [55]:
np.mean(A)

0.6866297525053248

In [57]:
np.median(A)

0.6925315900777659

In [58]:
np.std(A)

0.18503673441768229

Indexing, cutting

In [59]:
A = np.arange(20)
A

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19])

In [60]:
# A[idx], A[start:stop], A[:stop], A[start:]

In [61]:
A[2]

2

In [62]:
A[2:]

array([ 2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17, 18,
       19])

In [63]:
A[:2]

array([0, 1])

In [64]:
A[[0, 2]]

array([0, 2])

In [65]:
A[-1]

19

In [66]:
A[10:15]

array([10, 11, 12, 13, 14])

In [68]:
A = A.reshape(4, 5)
A

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19]])

In [69]:
A[0]

array([0, 1, 2, 3, 4])

In [70]:
A[:, 0]

array([ 0,  5, 10, 15])

In [71]:
A[:, -1]

array([ 4,  9, 14, 19])

In [72]:
A[1, 3]

8

In [74]:
A[1:3, 1:4]

array([[ 6,  7,  8],
       [11, 12, 13]])

In [77]:
A[1, 2] = 14
A

array([[ 0,  1,  2,  3,  4],
       [ 5,  6, 14,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19]])

Iterationg through array

In [78]:
A

array([[ 0,  1,  2,  3,  4],
       [ 5,  6, 14,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19]])

In [79]:
for row in A:
  print(row)

[0 1 2 3 4]
[ 5  6 14  8  9]
[10 11 12 13 14]
[15 16 17 18 19]


In [80]:
for row in A:
  print(row[:3])

[0 1 2]
[ 5  6 14]
[10 11 12]
[15 16 17]


In [81]:
for item in A.flat:
  print(item)

0
1
2
3
4
5
6
14
8
9
10
11
12
13
14
15
16
17
18
19


Size of array

In [84]:
A.shape

(4, 5)

In [85]:
A.reshape(5, 4)

array([[ 0,  1,  2,  3],
       [ 4,  5,  6, 14],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19]])

In [86]:
A.ravel()

array([ 0,  1,  2,  3,  4,  5,  6, 14,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19])

In [87]:
A.T

array([[ 0,  5, 10, 15],
       [ 1,  6, 11, 16],
       [ 2, 14, 12, 17],
       [ 3,  8, 13, 18],
       [ 4,  9, 14, 19]])

Logic masks

In [90]:
A = np.arange(start = -10, stop = 10, step = 0.5)
A = A.reshape(10, -1)
A

array([[-10. ,  -9.5,  -9. ,  -8.5],
       [ -8. ,  -7.5,  -7. ,  -6.5],
       [ -6. ,  -5.5,  -5. ,  -4.5],
       [ -4. ,  -3.5,  -3. ,  -2.5],
       [ -2. ,  -1.5,  -1. ,  -0.5],
       [  0. ,   0.5,   1. ,   1.5],
       [  2. ,   2.5,   3. ,   3.5],
       [  4. ,   4.5,   5. ,   5.5],
       [  6. ,   6.5,   7. ,   7.5],
       [  8. ,   8.5,   9. ,   9.5]])

In [91]:
A > 0

array([[False, False, False, False],
       [False, False, False, False],
       [False, False, False, False],
       [False, False, False, False],
       [False, False, False, False],
       [False,  True,  True,  True],
       [ True,  True,  True,  True],
       [ True,  True,  True,  True],
       [ True,  True,  True,  True],
       [ True,  True,  True,  True]])

In [92]:
A[A > 0]

array([0.5, 1. , 1.5, 2. , 2.5, 3. , 3.5, 4. , 4.5, 5. , 5.5, 6. , 6.5,
       7. , 7.5, 8. , 8.5, 9. , 9.5])

In [94]:
np.bitwise_and(A > -5, A < 5)

array([[False, False, False, False],
       [False, False, False, False],
       [False, False, False,  True],
       [ True,  True,  True,  True],
       [ True,  True,  True,  True],
       [ True,  True,  True,  True],
       [ True,  True,  True,  True],
       [ True,  True, False, False],
       [False, False, False, False],
       [False, False, False, False]])

In [95]:
A[np.bitwise_and(A > -5, A < 5)]

array([-4.5, -4. , -3.5, -3. , -2.5, -2. , -1.5, -1. , -0.5,  0. ,  0.5,
        1. ,  1.5,  2. ,  2.5,  3. ,  3.5,  4. ,  4.5])

In [96]:
np.bitwise_or(A < -5, A > 5)

array([[ True,  True,  True,  True],
       [ True,  True,  True,  True],
       [ True,  True, False, False],
       [False, False, False, False],
       [False, False, False, False],
       [False, False, False, False],
       [False, False, False, False],
       [False, False, False,  True],
       [ True,  True,  True,  True],
       [ True,  True,  True,  True]])