<a href="https://colab.research.google.com/github/PiotrSzewerniak/data-science/blob/main/linear_algebra.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [2]:
import numpy as np

Length of vector in $R^{2}$

In [5]:
v1 = np.array([-1, 4])
v1

array([-1,  4])

In [6]:
np.linalg.norm(v1)

4.123105625617661

Length of vector in $R^{n}$

In [7]:
v2 = np.array([-10, 10, 13])
np.linalg.norm(v2)

19.209372712298546

Distane between points

In [11]:
p = np.array([3, 0])
q = np.array([0, 4])

np.linalg.norm(p - q)

5.0

In [12]:
p = np.array([3, 0, 1])
q = np.array([0, 4, 2])

np.linalg.norm(p - q)

5.0990195135927845

Multiplying matrices

A - matrix $m$ $x$ $n$

B - matrix $n$ $x$ $p$

C - matrix $m$ $x$ $p$

Number of columns from left must be equal to number of rows at right

In [17]:
X = np.array([[5, 3], [3, 9]])
Y = np.array([[1], [-1]])
print(X, "\n")
print(Y)

[[5 3]
 [3 9]] 

[[ 1]
 [-1]]


In [20]:
Z = np.dot(X, Y)
Z

array([[ 2],
       [-6]])

In [22]:
X = np.array([[2, -1, 3],
              [3, 1, 0]])
Y = np.array([[2, 1, -1],
              [0, -1, 2],
              [3, 2, 0]])
print(X, "\n")
print(Y)

[[ 2 -1  3]
 [ 3  1  0]] 

[[ 2  1 -1]
 [ 0 -1  2]
 [ 3  2  0]]


In [23]:
np.dot(X, Y)

array([[13,  9, -4],
       [ 6,  2, -1]])

Matrix determinant - wyznacznik (Sarrus method)

In [25]:
A = np.array([[2, 4], [-1, 3]])
round(np.linalg.det(A))

10

Matrix trace - sum of diagonals

In [27]:
A = np.array([[2, 4], [-1, 3]])
np.trace(A)

5

Identity matrix - jednostkowa

In [28]:
np.eye(5, 4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.],
       [0., 0., 0., 0.]])

Inverse matrix - odwrotna

Square matrix $AB = BA = I$

In [30]:
B = np.linalg.inv(A)
B

array([[ 0.3, -0.4],
       [ 0.1,  0.2]])

In [32]:
np.set_printoptions(precision = 4, suppress = True)
np.dot(A, B)

array([[1., 0.],
       [0., 1.]])

In [33]:
np.dot(B, A)

array([[ 1., -0.],
       [ 0.,  1.]])

Transpose

In [34]:
np.transpose(A)

array([[ 2, -1],
       [ 4,  3]])

In [35]:
A.T

array([[ 2, -1],
       [ 4,  3]])

System of equations

\begin{cases}
  2x + 4y = 10 \\
  x - y = -1
\end{cases}

In [40]:
A = np.array([[2, 4], [1, -1]])
print(A)

[[ 2  4]
 [ 1 -1]]


In [41]:
B = np.array([[10], [-1]])
print(B)

[[10]
 [-1]]


In [42]:
A_inv = np.linalg.inv(A)
X = np.dot(A_inv, B)
X

array([[1.],
       [2.]])